on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

env:
  DOTFILES_BRANCH: ${{ github.head_ref || github.ref_name || 'master' }}

name: Build and Test dotfiles

jobs:
  build-macos:
    name: Build and Test macOS
    runs-on: macos-latest
    strategy:
      matrix:
        usage:
          - personal
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run installer
        run: |
          CI_USAGE=${{ matrix.usage }} sh install.sh

      - name: Install zunit
        run: |
          brew install zunit-zsh/zunit/zunit

      - name: Run test suite
        run: |
          CI_USAGE=${{ matrix.usage }} zunit --output-text

  build:
    name: Build and Test Ubuntu Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        usage:
          - personal
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install zsh

      - name: Run installer
        run: |
          sh install.sh
        shell: zsh {0}

      - name: Install zunit
        run: |
          brew install zunit-zsh/zunit/zunit
        shell: zsh {0}

      - name: Run test suite
        run: |
          CI_USAGE=${{ matrix.usage }} zunit --output-text
        shell: zsh {0}

  build-docker-container:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        usage:
          - personal
        os:
          - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And Install Dotfiles
        id: build
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          platforms: linux/amd64
          file: ./.github/.cicd/${{ matrix.os }}/Dockerfile
          push: false
          load: true
          tags: twitchel/dotfiles:${{ matrix.os }}-${{ matrix.usage }}-latest
          build-args: |
            DOTFILES_BRANCH=${{ env.DOTFILES_BRANCH }}
            CI_USAGE=${{ matrix.usage }}

      - name: Run test suite
        uses: addnab/docker-run-action@v3
        with:
          image: twitchel/dotfiles:${{ matrix.os }}-${{ matrix.usage }}-latest
          options: -v ${{ github.workspace }}:/home/docker-ci/.output
          shell: zsh
          run: |
            CI_USAGE=${{ matrix.usage }} zunit --output-text
