on:
  pull_request:
  workflow_dispatch:

env:
  DOTFILES_BRANCH: ${{ github.head_ref || github.ref_name || 'master' }}
  CI: personal

name: Build and Test Ubuntu Server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install zsh

      - name: Run installer
        run: |
          sh install.sh
        shell: zsh {0}