on:
  pull_request:
  workflow_dispatch:

env:
  DOTFILES_BRANCH: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          platforms: linux/amd64
          file: ./tests/${{ matrix.os }}/Dockerfile
          push: false
          build-args: |
            DOTFILES_BRANCH=${{ env.DOTFILES_BRANCH }}
