on:
  pull_request:
  workflow_dispatch:

env:
  DOTFILES_BRANCH: ${{ github.head_ref || github.ref_name || 'master' }}
  CI: personal

name: Build and Test macOS

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run installer
        run: |
          sh install.sh
